/// Cross-language mel parity test: Python reference vs Dart implementation.
///
/// Loads the fixture generated by tools/mandarin_grader/tests/test_mel_parity.py
/// and asserts that the Dart MelExtractor produces a spectrogram within 1e-3
/// max absolute error per element compared to the Python reference.
///
/// Run the Python test first to (re-)generate the fixture:
///   cd tools/mandarin_grader
///   uv run python tests/test_mel_parity.py
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:speak_to_learn/features/ml_inference/data/mel_extractor.dart';

void main() {
  group('MelExtractor Python parity', () {
    late Map<String, dynamic> fixture;
    late List<double> audioSamples;
    late List<List<double>> referenceMel;
    late int nMels;
    late int sampleRate;
    late int nFft;
    late int hopLength;

    setUpAll(() {
      // Resolve fixture path relative to the project root.
      // When running with `flutter test` the cwd is the package root
      // (apps/mobile_flutter).
      final fixturePath = 'test/fixtures/mel_parity_reference.json';
      final file = File(fixturePath);

      if (!file.existsSync()) {
        throw StateError(
          'Fixture not found at $fixturePath. '
          'Run `uv run python tests/test_mel_parity.py` inside '
          'tools/mandarin_grader to generate it.',
        );
      }

      final raw = file.readAsStringSync();
      fixture = json.decode(raw) as Map<String, dynamic>;

      audioSamples = (fixture['audio_samples'] as List<dynamic>)
          .map((v) => (v as num).toDouble())
          .toList();

      referenceMel = (fixture['mel'] as List<dynamic>).map((row) {
        return (row as List<dynamic>)
            .map((v) => (v as num).toDouble())
            .toList();
      }).toList();

      nMels = fixture['n_mels'] as int;
      sampleRate = fixture['sample_rate'] as int;
      nFft = fixture['n_fft'] as int;
      hopLength = fixture['hop_length'] as int;
    });

    test('fixture loads correctly', () {
      expect(audioSamples.length, equals(16000));
      expect(referenceMel.length, equals(80));
      expect(referenceMel[0].length, greaterThan(0));
      expect(nMels, equals(80));
      expect(sampleRate, equals(16000));
      expect(nFft, equals(400));
      expect(hopLength, equals(160));
    });

    test(
      'Dart mel matches Python reference within 1e-3 max absolute error',
      () {
        final extractor = MelExtractor(
          nMels: nMels,
          sampleRate: sampleRate,
          hopLength: hopLength,
          winLength: nFft,
          nFft: nFft,
          fmin: 0.0,
          fmax: sampleRate / 2.0,
        );

        final dartMel = extractor.extract(audioSamples);

        // Shape must match
        expect(
          dartMel.length,
          equals(referenceMel.length),
          reason: 'Number of mel bins must match',
        );
        expect(
          dartMel[0].length,
          equals(referenceMel[0].length),
          reason: 'Number of time frames must match',
        );

        // Check max absolute error across all bins and frames
        const maxAllowedError = 1e-3;
        var maxError = 0.0;
        var maxErrorBin = 0;
        var maxErrorFrame = 0;

        for (var i = 0; i < referenceMel.length; i++) {
          for (var t = 0; t < referenceMel[i].length; t++) {
            final err = (dartMel[i][t] - referenceMel[i][t]).abs();
            if (err > maxError) {
              maxError = err;
              maxErrorBin = i;
              maxErrorFrame = t;
            }
          }
        }

        expect(
          maxError,
          lessThan(maxAllowedError),
          reason:
              'Max absolute error $maxError at bin=$maxErrorBin '
              'frame=$maxErrorFrame exceeds threshold $maxAllowedError',
        );
      },
    );

    test('Dart mel has finite values', () {
      final extractor = MelExtractor(
        nMels: nMels,
        sampleRate: sampleRate,
        hopLength: hopLength,
        winLength: nFft,
        nFft: nFft,
        fmin: 0.0,
        fmax: sampleRate / 2.0,
      );

      final dartMel = extractor.extract(audioSamples);

      for (var i = 0; i < dartMel.length; i++) {
        for (var t = 0; t < dartMel[i].length; t++) {
          expect(
            dartMel[i][t].isFinite,
            isTrue,
            reason: 'Non-finite value at bin=$i frame=$t',
          );
        }
      }
    });
  });
}
